// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENHJQ56DagWdcb2eRgpIpLSdAZU6eDNE',
    appId: '1:569463280770:web:0effbd636b415fdaf6509b',
    messagingSenderId: '569463280770',
    projectId: 'projectsistem-650aa',
    authDomain: 'projectsistem-650aa.firebaseapp.com',
    storageBucket: 'projectsistem-650aa.firebasestorage.app',
    measurementId: 'G-K4TX02GP6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KC_-q0-UnaW0TN_oOodzhe0XsWTAQ9Q',
    appId: '1:569463280770:android:ccfe729fe4818320f6509b',
    messagingSenderId: '569463280770',
    projectId: 'projectsistem-650aa',
    storageBucket: 'projectsistem-650aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBijtkqJByFYhw5W-TTJQb1WwGBaZ7Bksw',
    appId: '1:569463280770:ios:756014162d508bf3f6509b',
    messagingSenderId: '569463280770',
    projectId: 'projectsistem-650aa',
    storageBucket: 'projectsistem-650aa.firebasestorage.app',
    iosBundleId: 'com.example.projectsistem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBijtkqJByFYhw5W-TTJQb1WwGBaZ7Bksw',
    appId: '1:569463280770:ios:756014162d508bf3f6509b',
    messagingSenderId: '569463280770',
    projectId: 'projectsistem-650aa',
    storageBucket: 'projectsistem-650aa.firebasestorage.app',
    iosBundleId: 'com.example.projectsistem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENHJQ56DagWdcb2eRgpIpLSdAZU6eDNE',
    appId: '1:569463280770:web:3e5dc0727ef38e7ff6509b',
    messagingSenderId: '569463280770',
    projectId: 'projectsistem-650aa',
    authDomain: 'projectsistem-650aa.firebaseapp.com',
    storageBucket: 'projectsistem-650aa.firebasestorage.app',
    measurementId: 'G-NRDNH15BET',
  );
}
